apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
  # annotations:
  #   recipients.argocd-notifications.argoproj.io: "slack:jenkins"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet:
        libs:
          - vendored
      recurse: true
    path: 
    repoURL: https://github.com/sibylobodoekwe/kubernetes-iaac-microservice.git 
    targetRevision: HEAD
  syncPolicy:
    automated: {}