apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  # Add labels to your application object.
  labels:
    name: logging
spec:
  # The project the application belongs to.
  project: default
  # Source of the application manifests
  source:
    repoURL: https://github.com/sibylobodoekwe/kubernetes-iaac-microservice.git 
    path: logging
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-logging