apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sockshop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  # Add labels to your application object.
  labels:
    name: sockshop
spec:
  # The project the application belongs to.
  project: default
  # Source of the application manifests
  source:
    repoURL: https://github.com/sibylobodoekwe/kubernetes-iaac-microservice.git  
    targetRevision: HEAD 
    path: manifests
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: sock-shop