apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: manifest-metrics
    app.kubernetes.io/version: 2.3.0
  name: manifest-metrics
  namespace: kube-system
