# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mongo-pvc
# spec:
#   storageClassName: "gp3"
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi