apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sockshop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: sockshop
spec:
  project: default
  source:
    repoURL: https://github.com/sibylobodoekwe/gitops-argocd
    targetRevision: HEAD 
    path: manifests
  # Cluster Destination and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: sock-shop
